# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='address',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='message',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='pincode',
        ),
    ]
